#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Jun 13 14:33:36 BST 2022
# SW Build 3526262 on Mon Apr 18 15:47:01 MDT 2022
#
# IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim axi_dma_wrapper_behav -key {Behavioral:sim_2:Functional:axi_dma_wrapper} -tclbatch axi_dma_wrapper.tcl -protoinst "protoinst_files/axi_dma.protoinst" -log simulate.log"
xsim axi_dma_wrapper_behav -key {Behavioral:sim_2:Functional:axi_dma_wrapper} -tclbatch axi_dma_wrapper.tcl -protoinst "protoinst_files/axi_dma.protoinst" -log simulate.log

