# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/axi_dma/axi_dma.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma || ORIG_REF_NAME==axi_dma} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_processing_system7_0_0/axi_dma_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_processing_system7_0_0 || ORIG_REF_NAME==axi_dma_processing_system7_0_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_axi_dma_0_0/axi_dma_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_axi_dma_0_0 || ORIG_REF_NAME==axi_dma_axi_dma_0_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_xbar_0/axi_dma_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_xbar_0 || ORIG_REF_NAME==axi_dma_xbar_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_ps7_0_axi_periph_0/axi_dma_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_ps7_0_axi_periph_0 || ORIG_REF_NAME==axi_dma_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_rst_ps7_0_100M_0/axi_dma_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_rst_ps7_0_100M_0 || ORIG_REF_NAME==axi_dma_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_axi_mem_intercon_0/axi_dma_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_axi_mem_intercon_0 || ORIG_REF_NAME==axi_dma_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_axi_mem_intercon_1_0/axi_dma_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_axi_mem_intercon_1_0 || ORIG_REF_NAME==axi_dma_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_example_0_2/axi_dma_example_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_example_0_2 || ORIG_REF_NAME==axi_dma_example_0_2} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_auto_pc_0/axi_dma_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_auto_pc_0 || ORIG_REF_NAME==axi_dma_auto_pc_0} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_auto_pc_1/axi_dma_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_auto_pc_1 || ORIG_REF_NAME==axi_dma_auto_pc_1} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_auto_pc_2/axi_dma_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_auto_pc_2 || ORIG_REF_NAME==axi_dma_auto_pc_2} -quiet] -quiet

# IP: bd/axi_dma/ip/axi_dma_auto_us_0/axi_dma_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_dma_auto_us_0 || ORIG_REF_NAME==axi_dma_auto_us_0} -quiet] -quiet

# XDC: /home/e2/axi_dma/axi_dma.gen/sources_1/bd/axi_dma/axi_dma_ooc.xdc
