# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/e2/axi_dma/axi_dma.srcs/sources_1/bd/axi_dma/ip/axi_dma_processing_system7_0_0/axi_dma_processing_system7_0_0.xci
# IP: The module: 'axi_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e2/axi_dma/axi_dma.gen/sources_1/bd/axi_dma/ip/axi_dma_processing_system7_0_0/axi_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/e2/axi_dma/axi_dma.srcs/sources_1/bd/axi_dma/ip/axi_dma_processing_system7_0_0/axi_dma_processing_system7_0_0.xci
# IP: The module: 'axi_dma_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/e2/axi_dma/axi_dma.gen/sources_1/bd/axi_dma/ip/axi_dma_processing_system7_0_0/axi_dma_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dma_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
